//
// Created by Immortal Jreey on 2025/3/18.
//

#ifndef ESP32_TEST_SUBIOTCONFIG_H
#define ESP32_TEST_SUBIOTCONFIG_H

#define SUB_IOT_SYSTEM_STATE_LED_PIN 2
#define SUB_IOT_SYSTEM_FACTORY_BLE_NAME "ESP32_Factory_1"


//#if !defined(SUB_IOT_SYSTEM_STATE_LED_PIN)
//#endif
//
//#if !defined(SUB_IOT_SYSTEM_FACTORY_BLE_NAME)
//
//#endif


typedef enum {
    WORK_STATE_INIT,
    WORK_STATE_FACTORY_CONFIG,
    WORK_STATE_BLE_CONFIG,
    WORK_STATE_WIFI_CONNECTED,
    WORK_STATE_MQTT_CONNECTED,
    WORK_STATE_WIFI_ERROR,
    WORK_STATE_MQTT_ERROR,
    WORK_STATE_WORKING

}WorkState;

#endif //ESP32_TEST_SUBIOTCONFIG_H
